<?xml version="1.0"?>
<!DOCTYPE featureList [
	<!ELEMENT featureList (pluginFolder?,feature+,aggregator*)>
	<!ELEMENT pluginFolder (#PCDATA)>
	<!ELEMENT feature (class , on?)>
	<!ELEMENT class (#PCDATA) >
	<!ELEMENT on EMPTY>
	<!ELEMENT aggregator (#PCDATA)>
]>

<featureList>
        <pluginFolder>file:///private/Network/Servers/borges.mt.lan/Volumes/home/mcennis/Documents/workspace/ScratchSpace/</pluginFolder>
	<feature>
		<class>jAudioFeatureExtractor.AudioFeatures.MagnitudeSpectrum</class>
	</feature>
	<feature>
		<class>jAudioFeatureExtractor.AudioFeatures.PowerSpectrum</class>
	</feature>
	<feature>
		<class>jAudioFeatureExtractor.AudioFeatures.FFTBinFrequencies</class>
	</feature>
	<feature>
		<class>jAudioFeatureExtractor.AudioFeatures.SpectralCentroid</class>
	</feature>
	<feature>
		<class>jAudioFeatureExtractor.AudioFeatures.SpectralRolloffPoint</class>
	</feature>
    <feature>
        <class>jAudioFeatureExtractor.AudioFeatures.ZernikeMoments</class>
    </feature>
    <feature>
        <class>jAudioFeatureExtractor.AudioFeatures.ZernikeMomentsBeatHistogram</class>
    </feature>
    <feature>
		<class>jAudioFeatureExtractor.AudioFeatures.SpectralFlux</class>
	</feature>
	<feature>
		<class>jAudioFeatureExtractor.AudioFeatures.Compactness</class>
	</feature>
	<feature>
		<class>jAudioFeatureExtractor.AudioFeatures.SpectralVariability</class>
	</feature>
	<feature>
		<class>jAudioFeatureExtractor.AudioFeatures.RMS</class>
	</feature>
	<feature>
		<class>jAudioFeatureExtractor.AudioFeatures.FractionOfLowEnergyWindows</class>
	</feature>
	<feature>
		<class>jAudioFeatureExtractor.AudioFeatures.ZeroCrossings</class>
	</feature>
	<feature>
		<class>jAudioFeatureExtractor.AudioFeatures.BeatHistogram</class>
	</feature>
	<feature>
		<class>jAudioFeatureExtractor.AudioFeatures.BeatHistogramLabels</class>
	</feature>
	<feature>
		<class>jAudioFeatureExtractor.AudioFeatures.StrongestBeat</class>
	</feature>
	<feature>
		<class>jAudioFeatureExtractor.AudioFeatures.BeatSum</class>
	</feature>
	<feature>
		<class>jAudioFeatureExtractor.AudioFeatures.StrengthOfStrongestBeat</class>
	</feature>
	<feature>
		<class>jAudioFeatureExtractor.AudioFeatures.StrongestFrequencyViaZeroCrossings</class>
	</feature>
	<feature>
		<class>jAudioFeatureExtractor.AudioFeatures.StrongestFrequencyViaSpectralCentroid</class>
	</feature>
	<feature>
		<class>jAudioFeatureExtractor.AudioFeatures.StrongestFrequencyViaFFTMax</class>
	</feature>
	<feature>
		<class>jAudioFeatureExtractor.AudioFeatures.MFCC</class>
	</feature>
	<feature>
		<class>jAudioFeatureExtractor.AudioFeatures.ConstantQ</class>
	</feature>
	<feature>
		<class>jAudioFeatureExtractor.AudioFeatures.LPC</class>
	</feature>
	<feature>
		<class>jAudioFeatureExtractor.AudioFeatures.PeakFinder</class>
	</feature>
	<feature>
		<class>jAudioFeatureExtractor.AudioFeatures.HarmonicSpectralCentroid</class>
	</feature>
	<feature>
		<class>jAudioFeatureExtractor.AudioFeatures.HarmonicSpectralFlux</class>
	</feature>
	<feature>
		<class>jAudioFeatureExtractor.AudioFeatures.HarmonicSpectralSmoothness</class>
	</feature>
	<feature>
		<class>jAudioFeatureExtractor.AudioFeatures.RelativeDifferenceFunction</class>
	</feature>
	<feature>
	  <class>jAudioFeatureExtractor.AudioFeatures.AreaMoments</class>
	</feature>
	<feature>
	  <class>jAudioFeatureExtractor.AudioFeatures.AreaMomentsMFCC</class>
	</feature>
	<feature>
	  <class>jAudioFeatureExtractor.AudioFeatures.AreaMomentsLogConstantQ</class>
	</feature>
	<feature>
	  <class>jAudioFeatureExtractor.AudioFeatures.AreaMomentsConstantQMFCC</class>
	</feature>
    <feature>
        <class>jAudioFeatureExtractor.AudioFeatures.AreaMomentsBeatHistogram</class>
    </feature>
	<feature>
	  <class>jAudioFeatureExtractor.AudioFeatures.ConstantQ</class>
      <on/>
	</feature>
	<feature>
	  <class>jAudioFeatureExtractor.AudioFeatures.LogConstantQ</class>
	</feature>
	<feature>
	  <class>jAudioFeatureExtractor.AudioFeatures.ConstantQMFCC</class>
	</feature>
	<feature>
	  <class>jAudioFeatureExtractor.AudioFeatures.Chroma</class>
	</feature>
    <feature>
	  <class>jAudioFeatureExtractor.AudioFeatures.AreaPolynomialApproximation</class>
	</feature>
	<feature>
	  <class>jAudioFeatureExtractor.AudioFeatures.AreaPolynomialApproximationConstantQMFCC</class>
	</feature>
	<feature>
	  <class>jAudioFeatureExtractor.AudioFeatures.AreaPolynomialApproximationLogConstantQ</class>
	</feature>
    <feature>
        <class>jAudioFeatureExtractor.AudioFeatures.TraditionalAreaMoments</class>
    </feature>
	<aggregator>jAudioFeatureExtractor.Aggregators.Mean</aggregator>
	<aggregator>jAudioFeatureExtractor.Aggregators.StandardDeviation</aggregator>
	<aggregator>jAudioFeatureExtractor.Aggregators.AreaMoments</aggregator>
	<aggregator>jAudioFeatureExtractor.Aggregators.MFCC</aggregator>
	<aggregator>jAudioFeatureExtractor.Aggregators.MultipleFeatureHistogram</aggregator>
	<aggregator>jAudioFeatureExtractor.Aggregators.AreaPolynomialApproximation</aggregator>
    <aggregator>jAudioFeatureExtractor.Aggregators.ZernikeMoments</aggregator>
</featureList>
